### Creating tensors in pytorch


In [1]:
import numpy as np
import torch

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
#1. We can create tensor from a list or a numpy array.
np.set_printoptions(precision=3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [ ]:
t_ones = torch.ones([2,3]) # a matrix of 1's
print(t_ones.shape) # shape of a tensor
print(t_ones)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.0722, 0.7258, 0.4639],
        [0.6537, 0.7186, 0.3014]])


### Manipulating data type and shape of a tensor


In [7]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


Certain operations require tensors to have a certain number of dimension(this is, rank), associated with a certain number of elements(shape). Thus, we need to change the shape of a tensor, add a new dimension.

In [ ]:
## Transposing a tensor
t = torch.rand([3,5])
t_tr = torch.transpose(t, 0, 1) #swap dimension 0 and dimension 1.
print(t.shape,' --> ',t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


In [11]:
## Reshaping a tensor
t = torch.zeros(30)
t_reshape = t.reshape(5,6)
print(t_reshape.shape)

torch.Size([5, 6])


In [13]:
## Removing unnecessary dimensions (dimensions that have size 1)
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


### Applying mathematical operatorions to tensors

In [14]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5,2) - 1 # generate random numbers from normal distribution N(0,1)
t2 = torch.normal(mean=0, std = 1, size = (5,2))

# to calculate element-wise product of t1 and t2
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [19]:
# Calculating some statistics along an axis
t4 = torch.mean(t1, axis = 0)
print(t4)
print(torch.sum(t2, axis = 0))
print(torch.std(t2))

tensor([-0.1373,  0.2028])
tensor([-1.7636,  1.1434])
tensor(0.8870)


In [20]:
## Matrix multiplication
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [21]:
t5 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t5)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [22]:
## Calculating Lp norm of a matrix
norm_t1 = torch.linalg.norm(t1, ord = 2, dim = 1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


## Split, stack and concatenate tensor